import React from 'react'
import Head from 'next/head';
import Layout from '../../hoc/Layout/Layout';
import Categories from '../../containers/Categories/Categories';


export default function ListCategories() {
    return (
        <>
          <Head>
            <title>List Categories - BookLib App</title>
            <meta name="description" content="Generated by create next app" />
          </Head>
          <Layout>
            <div className="all--category">
              <h3 className="display-4">All Categories</h3>
              <div className="container">
                <Categories simiplified={false} />
              </div>
            </div>
          </Layout>
        
      </>
    )
}
