import React from 'react'
import Head from 'next/head';
import Layout from '../../hoc/Layout/Layout';
import Categories from '../../containers/Categories/Categories';


export default function ListCategories() {
    return (
        <>
          <Head>
            <title>List Categories - BookLib App</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
          <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet"></link>
          </Head>
          <Layout>
            <div className="all--category">
              <h3 className="display-4">All Categories</h3>
              <div className="container">
                <Categories simiplified={false} />
              </div>
            </div>
          </Layout>
        
      </>
    )
}
