import React from 'react';
import Head from 'next/head';
import Layout from '../../hoc/Layout/Layout';


export default function Favorites() {
    return (
        <>
      <Head>
        <title>Favorites - BookLib App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
        <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet"></link>
      </Head>
      <Layout>
          favorites
      </Layout>
      
    </>
    )
}
