import React from 'react';
import Head from 'next/head';
import Layout from '../../hoc/Layout/Layout';

export default function Book() {
    return (
        <>
        <Head>
          <title>Add Book - BookLib App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Layout>
          <div className="top--book">
             <h3 className="display-4">Add Book</h3>
          </div>
        </Layout>
        
      </>
    )
} 
