import React from 'react';
import Head from 'next/head';
import Layout from '../../hoc/Layout/Layout';
import Books from '../../containers/Books/Books';



export default function ListBooks() {

    return (
        <>
        <Head>
          <title>List Books - BookLib App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
          <link rel="preconnect" href="https://fonts.googleapis.com" />
          <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@400;500;600;700;800;900&display=swap" rel="stylesheet"></link>
          <link href="https://fonts.googleapis.com/css2?family=Architects+Daughter&display=swap" rel="stylesheet"></link>
        </Head>
        <Layout>
          <div className="top--book">
             <h3 className="display-4">All Books</h3>
            <Books simiplified={false} />
          </div>
        </Layout>
        
      </>
    )
}
