import React from 'react';
import Head from 'next/head';
import Layout from '../../hoc/Layout/Layout';
import Books from '../../containers/Books/Books';



export default function ListBooks() {

    return (
        <>
        <Head>
          <title>List Books - BookLib App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <Layout>
          <div className="top--book">
             <h3 className="display-4">All Books</h3>
            <Books simiplified={false} />
          </div>
        </Layout>
        
      </>
    )
}
